//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_guildlines
    {
        public int audit_guildlines_id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public string description { get; set; }
        public string notes { get; set; }
        public string attach_audit_guildline { get; set; }
        public string attach_other { get; set; }
        public string userID { get; set; }
    }
}
