//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string company_name { get; set; }
        public string project_name { get; set; }
        public string department { get; set; }
        public string gender { get; set; }
        public string work_number { get; set; }
        public string mobile_number { get; set; }
        public string website_url { get; set; }
        public string website_title { get; set; }
        public string attach_photo { get; set; }
        public string about_contact { get; set; }
        public string userID { get; set; }
    }
}
