//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cor_rem_action
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public string project_name { get; set; }
        public string work_dept { get; set; }
        public string action_type { get; set; }
        public string action_name { get; set; }
        public string action_rem_by { get; set; }
        public string action_rem { get; set; }
        public string action_implimented { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string action_com_by { get; set; }
        public string results_of_actions { get; set; }
        public string staatus_of_action { get; set; }
        public string attachment { get; set; }
        public string userID { get; set; }
    }
}
