//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_audits
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public Nullable<System.DateTime> dbo_audit_date { get; set; }
        public string type_of_audit { get; set; }
        public string project_name { get; set; }
        public string description { get; set; }
        public string completed_by { get; set; }
        public string auditing_organization { get; set; }
        public string score { get; set; }
        public string notes { get; set; }
        public string attach_audits { get; set; }
        public string attach_other { get; set; }
        public string userID { get; set; }
    }
}
