//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_manual
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dbo_manual_date { get; set; }
        public Nullable<System.DateTime> development_date { get; set; }
        public Nullable<System.DateTime> revision_date { get; set; }
        public Nullable<System.DateTime> next_revision_date { get; set; }
        public string version_number { get; set; }
        public string update_number { get; set; }
        public string revised_by { get; set; }
        public string approved_by { get; set; }
        public string attach_dbo_manual { get; set; }
        public string attach_other { get; set; }
        public string userID { get; set; }
    }
}
