//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_protection_programs
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dbo_protection_programs_date { get; set; }
        public string project_name { get; set; }
        public string work_area_department { get; set; }
        public string description_of_program { get; set; }
        public string version_number { get; set; }
        public Nullable<System.DateTime> revision_date { get; set; }
        public Nullable<System.DateTime> next_revision_date { get; set; }
        public string notes { get; set; }
        public string attach_program { get; set; }
        public string attach_other { get; set; }
        public string userID { get; set; }
    }
}
