//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emerg_prep_practice
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public string project_name { get; set; }
        public string work_dept { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> dt_of_practice { get; set; }
        public string description { get; set; }
        public string response_time { get; set; }
        public string evaluation_notes { get; set; }
        public string corr_action_recomm { get; set; }
        public string attachment_1 { get; set; }
        public string attachment_2 { get; set; }
        public string attachment_3 { get; set; }
        public string attachment_4 { get; set; }
        public string userID { get; set; }
    }
}
