//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_information
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string currently_employed { get; set; }
        public string position { get; set; }
        public string project_name { get; set; }
        public string work_area_dept { get; set; }
        public string gender { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state_province { get; set; }
        public string postal_code { get; set; }
        public string home_number { get; set; }
        public string cell_number { get; set; }
        public string email_address { get; set; }
        public string medical_card_number { get; set; }
        public string drivers_license_class { get; set; }
        public string medical_condition { get; set; }
        public string insurance_coverage { get; set; }
        public string notes { get; set; }
        public string userID { get; set; }
    }
}
