//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class legal_other_requierments
    {
        public int id { get; set; }
        public Nullable<System.DateTime> legal_other_requierments_date { get; set; }
        public string description_of_requirements { get; set; }
        public string notes { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string attach_requirements { get; set; }
        public string userID { get; set; }
    }
}
