//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string work_department { get; set; }
        public string position { get; set; }
        public string doctor_name { get; set; }
        public string doctor_number { get; set; }
        public string medical_condition { get; set; }
        public string medications { get; set; }
        public string emergency_instructions { get; set; }
        public string attachments { get; set; }
        public string userID { get; set; }
    }
}
