//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qhsedbEntities : DbContext
    {
        public qhsedbEntities()
            : base("name=qhsedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audit_guildlines> audit_guildlines { get; set; }
        public virtual DbSet<company_information> company_information { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<cor_rem_action> cor_rem_action { get; set; }
        public virtual DbSet<dbo_audits> dbo_audits { get; set; }
        public virtual DbSet<dbo_manual> dbo_manual { get; set; }
        public virtual DbSet<dbo_protection_programs> dbo_protection_programs { get; set; }
        public virtual DbSet<detailed_incident_invest_rep> detailed_incident_invest_rep { get; set; }
        public virtual DbSet<disciplinary_action> disciplinary_action { get; set; }
        public virtual DbSet<early_safe_return_wp> early_safe_return_wp { get; set; }
        public virtual DbSet<emerg_prep_practice> emerg_prep_practice { get; set; }
        public virtual DbSet<emerg_rescue_plan> emerg_rescue_plan { get; set; }
        public virtual DbSet<general_information> general_information { get; set; }
        public virtual DbSet<general_safety_meetings> general_safety_meetings { get; set; }
        public virtual DbSet<hazard_nm_fin_rep> hazard_nm_fin_rep { get; set; }
        public virtual DbSet<hazard_sub_emp_exp> hazard_sub_emp_exp { get; set; }
        public virtual DbSet<journey_mgmt> journey_mgmt { get; set; }
        public virtual DbSet<legal_other_requierments> legal_other_requierments { get; set; }
        public virtual DbSet<medical> medicals { get; set; }
        public virtual DbSet<meeting_planning_work> meeting_planning_work { get; set; }
        public virtual DbSet<mgmt_rev_agenda> mgmt_rev_agenda { get; set; }
        public virtual DbSet<mgmt_rev_minute> mgmt_rev_minute { get; set; }
        public virtual DbSet<monthly_safety_summary> monthly_safety_summary { get; set; }
        public virtual DbSet<next_of_kin> next_of_kin { get; set; }
        public virtual DbSet<occupational_history_form> occupational_history_form { get; set; }
        public virtual DbSet<ohs_comm_agenda> ohs_comm_agenda { get; set; }
        public virtual DbSet<ohs_committee> ohs_committee { get; set; }
        public virtual DbSet<orientation_tr_mat> orientation_tr_mat { get; set; }
        public virtual DbSet<prob_solv_meet_rep> prob_solv_meet_rep { get; set; }
        public virtual DbSet<qualification> qualifications { get; set; }
        public virtual DbSet<return_to_work_plan> return_to_work_plan { get; set; }
        public virtual DbSet<safe_work_procedure> safe_work_procedure { get; set; }
        public virtual DbSet<tool_box_topic> tool_box_topic { get; set; }
        public virtual DbSet<train_aware_comp> train_aware_comp { get; set; }
        public virtual DbSet<witness_statement> witness_statement { get; set; }
        public virtual DbSet<worker_comp_insurace_reports_stats> worker_comp_insurace_reports_stats { get; set; }
    }
}
