//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class next_of_kin
    {
        public int id { get; set; }
        public string name { get; set; }
        public string kin_full_name { get; set; }
        public string gender { get; set; }
        public string relationship { get; set; }
        public string description { get; set; }
        public string home_phone { get; set; }
        public string cell_phone { get; set; }
        public string email_address { get; set; }
        public string address_option { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string state_province { get; set; }
        public string country { get; set; }
        public string userID { get; set; }
    }
}
