//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orientation_tr_mat
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string work_dept { get; set; }
        public string desc_train_ori { get; set; }
        public string notes { get; set; }
        public string orient_file_1 { get; set; }
        public string orient_fiile_2 { get; set; }
        public string orient_file_3 { get; set; }
        public string orient_file_4 { get; set; }
        public string userID { get; set; }
    }
}
