//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prob_solv_meet_rep
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public string project_name { get; set; }
        public string work_dept { get; set; }
        public string meeting_leader { get; set; }
        public string problem { get; set; }
        public string analysis { get; set; }
        public string corrective_action { get; set; }
        public string follow_up { get; set; }
        public string other_PAA { get; set; }
        public string attendance { get; set; }
        public string reviewed_by { get; set; }
        public string attachment_1 { get; set; }
        public string attchment_2 { get; set; }
        public string userID { get; set; }
    }
}
