//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class safe_work_procedure
    {
        public int id { get; set; }
        public string safe_work_procedure_description { get; set; }
        public Nullable<System.DateTime> development_date { get; set; }
        public string version_number { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public Nullable<System.DateTime> next_review_date { get; set; }
        public string swp_notes { get; set; }
        public string attach_other { get; set; }
        public string attach_swp { get; set; }
        public string userID { get; set; }
    }
}
