//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_comp_insurace_reports_stats
    {
        public int id { get; set; }
        public string worker_comp_insurace_reports_stats_date { get; set; }
        public string description { get; set; }
        public string project_name { get; set; }
        public string department_work_area { get; set; }
        public string details { get; set; }
        public string attachment_1 { get; set; }
        public string attachment_2 { get; set; }
        public string userID { get; set; }
    }
}
